// console.log(number1);
// console.log(number2);
// console.log(number3);
 var number1=3;
let number2=2.5;
const number3=0xff;
var fristName="salma";
var middleName='adel';
var lastName=`fathy`;
var flag=true;
// console.log("This is the External JavaScript file");
